name: extract_colors_from_image
description: Pick color from image (assets/network/file) and get color hexcodes.
version: 0.0.1
homepage: https://github.com/JamalSorani/extract-colors-from-image-package

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  clipboard: ^0.1.3
  flutter:
    sdk: flutter
  image: ^4.1.3
  image_picker: ^1.0.4
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg